
export const FETCH_UNIV_REQ = 'FETCH_UNIV_REQ';
export const FETCH_UNIV_SUCESS = 'FETCH_UNIV_SUCESS';
export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';
export const SET_PROGRAM_ITEM = 'SET_PROGRAM_ITEM';
export const DELETE_PROGRAM_ITEM = 'DELETE_PROGRAM_ITEM';
export const FETCH_BY_ID = 'FETCH_BY_ID';

